name: E2E testing
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker-compose build
    - name: Run the docker-compose file
      run: docker-compose up -d 
    - name: Run test suite
      run: docker-compose run nodejs npm run test:e2e
